// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bavwdyiekzjxytmmdfrd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJhdndkeWlla3pqeHl0bW1kZnJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwOTMwNTgsImV4cCI6MjA2ODY2OTA1OH0.tXv62iu_jOxSfT2llMhux1xng_VOOElDHWW0VGStBtU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});